### ISSUE TITLE
Build an adaptive app with adaptive layout: Android Basics with Compose: While running 

### ISSUE THREAD

**Issue by SergioTellezSanchez** [google-developer-training/basic-android-kotlin-compose-training-reply-app#10]
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.reply.test/androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
 
// That is promnt while trying to run the tests

**Comment by tugceaktepe** [comment]
Hello Sergio, 

The missing espresso dependency needs to be added. Once I added it, the test was able to run.I compared the test dependencies in the Cupcake app. Only this one was missing.

`    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.5.0'

Have a nice day.

**Comment by AAB999** [comment]
@tugceaktepe THANKS for the tip! I jus ran into the same Problem and that helped! 👍 😎
