### ISSUE TITLE
Build an adaptive app with adaptive layout: Android Basics with Compose

### ISSUE THREAD

**Issue by hhyeok1026** [google-developer-training/basic-android-kotlin-compose-training-reply-app#12]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-adaptive-content-for-large-screens?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-3%3Fhl%3Dko%26authuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-adaptive-content-for-large-screens#4

**In which task and step of the codelab can this issue be found?**
-  5. Add automated test for adaptive apps 
- ReplyAppStateRestorationTest.kt
- fun expandedDevice_selectedEmailEmailRetained_afterConfigChange()

**Describe the problem**
When running the test,
fun expandedDevice_selectedEmailEmailRetained_afterConfigChange() 
failed test 
because R.string.details_screen was not found.

Solved by checking that the solution code has the following content.

- ReplyDetailsScreen.kt
- fun ReplyDetailsScreen()
- .testTag(stringResource(id = R.string.details_screen)) 
in modifier to argument of LazyColumn

There is no mention of it in the codelab description.

**Comment by tugceaktepe** [comment]
Hello,

I still can not run this test because of this error: [14](https://github.com/google-developer-training/basic-android-kotlin-compose-training-reply-app/issues/14) Did you ever run this test successfully ?

**Comment by hhyeok1026** [comment]
@tugceaktepe

Solved by checking that the solution code has the following content.

ReplyDetailsScreen.kt
fun ReplyDetailsScreen()
.testTag(stringResource(id = R.string.details_screen))
in modifier to argument of LazyColumn
