### ISSUE TITLE
Build an adaptive app with dynamic navigation: Android Basics with Compose

### ISSUE THREAD

**Issue by williamFerrante** [google-developer-training/basic-android-kotlin-compose-training-reply-app#19]
Per the instructions in "Build an adaptive app with dynamic navigation", step 2 "App Overview", I downloaded the starter code and attempted a build. The project would not build. See attached message screenshot showing the "This project does not use the Gradle build system. We recommend that you migrate to using the Gradle build system." message. 

![image](https://user-images.githubusercontent.com/104443586/211054579-8ea4f522-24c7-47c5-8505-05f2118ca736.png)

**Comment by ScottyNZ** [comment]
Hi William, 
I also just started this Codelab. Downloaded the **starter** branch and it built and ran fine.

So it might be downloading it again an giving it another go.

good luck, 

Note: I'm using Android Studio Dolphin. I did not attempt any project updates (e.g. AGP updates, etc) prior to building.

**Comment by williamFerrante** [comment]
Hi Scotty,

I wound up importing the whole project into studio directly from github,
then changing branches to starter. That seemed to work.

Originally, I followed the instructions as stated in the codelab (download
starter and unpack, then open) and had the problems.

I'm also using Dolphin, Appreciate your help. Thanks!

Bill
