### ISSUE TITLE
Build an adaptive app with adaptive layout: Android Basics with Compose

### ISSUE THREAD

**Issue by pnwbob** [google-developer-training/basic-android-kotlin-compose-training-reply-app#35]
I was unable to see the preview for the Expanded type:
```
@Preview(showBackground = true, widthDp = 1000)
@Composable
fun ReplyAppExpandedPreview() {
    ReplyTheme {
        ReplyApp(
            windowSize = WindowWidthSizeClass.Expanded
        )
    }
}
```
All the other compose previews were successful. You can find the instructions [here](https://developer.android.com/codelabs/basic-android-kotlin-compose-adaptive-content-for-large-screens?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-4-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-adaptive-content-for-large-screens#1). This isn't really a problem with the instructions, it is more of an issue with Android Studio.

The Render Issues error output looks like this:
[error_output.txt](https://github.com/google-developer-training/basic-android-kotlin-compose-training-reply-app/files/11504492/error_output.txt)

**Comment by housewar** [comment]
In the Resource Manager, select the tab for Dimension (may have to press the ... menu)

The dimension for "profile_image_padding" is set to 16.dp, that should be 16dp (without the period).
