### ISSUE TITLE
My City app: Android Basics with Compose

### ISSUE THREAD

**Issue by Isanderthul** [google-developer-training/basic-android-kotlin-compose-training-reply-app#4]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-my-city?hl=en#0

**In which task and step of the codelab can this issue be found?**
index

**Describe the problem**
not tagged as an android app tutorial. 

**Additional information**
<img width="1083" alt="Screenshot 2022-08-19 at 08 18 46" src="https://user-images.githubusercontent.com/3693197/185555565-22aa7fb4-d5ba-40fb-97a8-55ebda9dd18c.png">

**Comment by osuleymanova** [comment]
@Isanderthul 
Thank you for reaching out to us and informing about this issue. The actions to fix it will be taken soon.
