### ISSUE TITLE
Build an adaptive app with dynamic navigation: Android Basics with Compose

### ISSUE THREAD

**Issue by ShayDeeJay** [google-developer-training/basic-android-kotlin-compose-training-reply-app#5]
Problem with setup, When initially introducing tablet mode aka, permanent navigation bar, the bottom navigation bar is still shown, this is not removed until later and not addressed in that section. Also,  the solution code does not at all work as it is intended.

**Comment by Zheitk** [comment]
Checking the solution, step 7 Implement a navigation drawer: they forgot to wrap the NavigationDrawerContent on a PermanentDrawerSheet composable.
