### ISSUE TITLE
Build an adaptive app with dynamic navigation: Android Basics with Compose

### ISSUE THREAD

**Issue by wysiwyg-data** [google-developer-training/basic-android-kotlin-compose-training-reply-app#9]
I have hit a strange behaviour: the Navigation Drawer composable (`PermanentNavigationDrawer(...)`) displays fine, but no content (defined by `content = { ReplyAppContent(...) }`) is visible (the inbox as a list of messages). Instead the Navigation Drawer extends all the way to the right edge.

System:
- Linux KUbuntu 22.04
- Android Studio Dolphin | 2031.3.1 Patch 1 Built Sept. 30, 2022
- Project: Reply app cloned from `$ git clone https://github.com/google-developer-training/basic-android-kotlin-compose-training-reply-app.git`
- Emulator: Resizable (Experimental) API 33
- Physical device: Samsung Nexus 10

The Navigation Drawer behaviour is consistent on both resizable emulator and Nexus device.

I have tried replacing the code inside the `content = { ReplyAppContent(...) }` with a simple text composable `content = { Text(...) }`. No text appears.

I am now going to try a Digital Ocean tutorial on Navigation Drawer (`https://www.digitalocean.com/community/tutorials/android-navigation-drawer-example-tutorial`) and see if the issue persists or gets solved.

**Comment by angiesasmita** [comment]
hi @wysiwyg-data could you give us a screenshot of the Navigation Drawer? Also if you could provide a fuller code snippet or which step of the codelab that causes this issue, it will really help reproduce the issue. Thanks! :)

**Comment by wysiwyg-data** [comment]
Hi @angiesasmita. Thank you for your prompt response.

1. The problem appears in Step 7, paragraph "Implement a navigation drawer" of the Codelab.

2. The offending code: 
`    if (navigationType == ReplyNavigationType.PERMANENT_NAVIGATION_DRAWER
        && replyUiState.isShowingHomepage) {
        PermanentNavigationDrawer(
            drawerContent = {
                NavigationDrawerContent(
                    selectedDestination = replyUiState.currentMailbox,
                    onTabPressed = onTabPressed,
                    navigationItemContentList = navigationItemContentList
                )
            }
        ) {
            ReplyAppContent(
                navigationType = navigationType,
                replyUiState = replyUiState,
                onTabPressed = onTabPressed,
                onEmailCardPressed = onEmailCardPressed,
                navigationItemContentList = navigationItemContentList,
                modifier = modifier
            )
        }
    } else {
...
}`
This code can be located in the `ReplyHomeScreen.kt`, starting line 94. Code taken from the downloadable solution: `$ git clone https://github.com/google-developer-training/basic-android-kotlin-compose-training-reply-app.git`
I noticed the syntax you're using for the `PermanentNavigationDrawer()` composable in the above code differs from the one found in the documentation  (`https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary#PermanentNavigationDrawer(kotlin.Function0,androidx.compose.ui.Modifier,kotlin.Function0)`).
I tried changing the code snippet above to strictly follow the documentation:
`    if (navigationType == ReplyNavigationType.PERMANENT_NAVIGATION_DRAWER
        && replyUiState.isShowingHomepage
    ) {
        PermanentNavigationDrawer(
            drawerContent = {
                NavigationDrawerContent(
                    selectedDestination = replyUiState.currentMailbox,
                    onTabPressed = onTabPressed,
                    navigationItemContentList = navigationItemContentList
                )
            },
            content = {
                ReplyAppContent(
                    navigationType = navigationType,
                    replyUiState = replyUiState,
                    onTabPressed = onTabPressed,
                    onEmailCardPressed = onEmailCardPressed,
                    navigationItemContentList = navigationItemContentList,
                    modifier = modifier
                )
            }
        )
    } else {
...
}`
However the error persists.

I am going to run some tests later today (NZ time) with the `PermanentNavigationDrawer()` composable, simplifying the code to a minimum in order to see if the error still shows up.
I understand the `PermanentNavigationDrawer()` composable is an experimental composable, and thus is subject to changes, and deprecation at any time. ;-)

I'll be in touch later.
Meanwhile it'd be good if you can reproduce the error.
![reply1](https://user-images.githubusercontent.com/104740524/201436880-64f85e87-9987-4591-90c5-45dedb98827a.png)

**Comment by wysiwyg-data** [comment]
Hi @angiesasmita. 
Here is my test code, which still won't display any content. I used the base code from the downloaded solution at the end of the codelab (`$ git clone https://github.com/google-developer-training/basic-android-kotlin-compose-training-reply-app.git`) and basically placed the minimum necessary code to display a navigation drawer in the `MainActivity.kt`.
Please see:
`package com.example.reply
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Drafts
import androidx.compose.material.icons.filled.Inbox
import androidx.compose.material.icons.filled.Report
import androidx.compose.material.icons.filled.Send
import androidx.compose.material3.*
import androidx.compose.material3.windowsizeclass.ExperimentalMaterial3WindowSizeClassApi
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.example.reply.data.local.LocalAccountsDataProvider
import com.example.reply.ui.*
import com.example.reply.ui.theme.ReplyTheme
`

**Comment by angiesasmita** [comment]
Hi @wysiwyg-data Thanks for flagging this issue. This bug appeared as we upgraded the material3 dependency. In the previous Material 3 version, we didn't need to specify the `PermanentAppDrawer` width. This is made more flexible in the newer version by using `PermanentDrawerSheet()` and specifying the width inside.

The bug has been fix in the code: https://github.com/google-developer-training/basic-android-kotlin-compose-training-reply-app/commit/9ee063ac67d27c904df08eaca7cd7a93f9387e87

and will be updated in the codelab too. 
Once again, Thank you for bringing this to our attention, we really appreciate it!
